name: dev-env
on:
  push:
    branches:
      - dev
jobs:
  deploy-dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker build -t ghcr.io/panus2544/bookinfo-ratings:dev .
      - run: docker images
      - run: docker push ghcr.io/panus2544/bookinfo-ratings:dev